---
abstract: 'foundation for oo GetOpt support'
author:
  - 'Eric Wilhelm @ <ewilhelm at cpan dot org>'
build_requires:
  Module::Build: 0.26
  Test::More: 0
configure_requires:
  Module::Build: 0.31
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.131490'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Getopt-Base
provides:
  Getopt::Base:
    file: lib/Getopt/Base.pm
    version: v0.0.3
  Getopt::Base::Accessors:
    file: lib/Getopt/Base.pm
requires:
  perl: 5.008000
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Getopt-Base
  homepage: http://scratchcomputing.com/
  license: http://dev.perl.org/licenses/
  repository: http://svn.scratchcomputing.com/Getopt-Base/trunk
version: v0.0.3
