---
name: Getopt-Base
version: v0.0.2
author:
  - 'Eric Wilhelm @ <ewilhelm at cpan dot org>'
abstract: foundation for oo GetOpt support
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Getopt-Base
  homepage: http://scratchcomputing.com/
  license: http://dev.perl.org/licenses/
  repository: http://svn.scratchcomputing.com/Getopt-Base/trunk
configure_requires:
  Module::Build: 0.31
requires:
  perl: 5.006002
build_requires:
  Module::Build: 0.26
  Test::More: 0
provides:
  Getopt::Base:
    file: lib/Getopt/Base.pm
    version: v0.0.2
  Getopt::Base::Accessors:
    file: lib/Getopt/Base.pm
generated_by: Module::Build version 0.3103
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
